window.PROJECTS = [
  {
    name: "Industrial solar, built for scale",
    location: "Andhra Pradesh",
    technology: "Solar",
    sector: "Industrial",
    capacity: "5",
    unit: "MW",
    generation: "7,500 MWh / year",
    carbon: "5,325 tCO\u2082e / year",
    status: "Operational",
    detail:
      "A ground-mounted solar concept serving daytime industrial demand. Inverter-level monitoring helps identify underperforming strings; scheduled inspection and cleaning support dependable output.",
  },
  {
    name: "Wind power on the southern coast",
    location: "Tamil Nadu",
    technology: "Wind",
    sector: "Utility",
    capacity: "20",
    unit: "MW",
    generation: "52,000 MWh / year",
    carbon: "36,920 tCO\u2082e / year",
    status: "Operational",
    detail:
      "A wind-farm concept pairing resource assessment with turbine siting and grid evacuation planning. Seasonal generation is reviewed against the expected resource profile.",
  },
  {
    name: "Energy that waits for you",
    location: "Karnataka",
    technology: "Storage",
    sector: "Commercial",
    capacity: "10",
    unit: "MWh",
    generation: "Storage; no generation",
    carbon: "Dispatch-dependent",
    status: "Commissioning",
    detail:
      "A 5 MW / 10 MWh battery concept designed for a two-hour discharge at rated power. Dispatch planning considers charging source, losses, tariffs and battery warranty constraints.",
  },
  {
    name: "Clean power for growing communities",
    location: "Telangana",
    technology: "Solar",
    sector: "Agriculture",
    capacity: "0.5",
    unit: "MW",
    generation: "750 MWh / year",
    carbon: "533 tCO\u2082e / year",
    status: "Operational",
    detail:
      "A solar agricultural concept matching irrigation schedules and farm demand to daytime generation. Seasonal water needs inform sizing and operating schedules.",
  },
  {
    name: "A more balanced energy mix",
    location: "Gujarat",
    technology: "Hybrid",
    sector: "Industrial",
    capacity: "12",
    unit: "MW",
    generation: "25,000 MWh / year",
    carbon: "17,750 tCO\u2082e / year",
    status: "In development",
    detail:
      "An 8 MW solar and 4 MW wind concept. Complementary production profiles can reduce variability, while grid studies establish export limits and protection requirements.",
  },
  {
    name: "A smarter commercial rooftop",
    location: "Maharashtra",
    technology: "Solar",
    sector: "Commercial",
    capacity: "1.2",
    unit: "MW",
    generation: "1,800 MWh / year",
    carbon: "1,278 tCO\u2082e / year",
    status: "Operational",
    detail:
      "A rooftop concept for a distribution campus. Structural assessment, safe maintenance access and interval consumption data shape the array layout and electrical design.",
  },
];
window.ARTICLES = [
  [
    "Solar",
    "The future of solar energy in India",
    "Why better planning matters as solar becomes part of everyday infrastructure.",
    "Solar is increasingly considered alongside building design, electricity demand and long-term operating costs. Rooftop and larger systems serve different needs, but both begin with resource assessment and a realistic understanding of when electricity is used.",
    "Start with twelve months of electricity bills and interval demand where available. Review usable area, shade, structural capacity and the point of connection before comparing proposals. Capacity alone cannot tell you how much energy a site will use productively.",
    "Compare assumptions about degradation, maintenance, inverter replacement and export compensation. Local approvals and tariff arrangements need verification for the actual site. A well-documented design and a clear operating plan are as important as selecting equipment.",
  ],
  [
    "Storage",
    "How batteries support renewable energy",
    "Moving energy from abundant hours to useful hours.",
    "Solar and wind production do not always coincide with demand. A battery stores electricity and supplies it later, helping manage short-term variation and demand peaks. It does not generate new energy and loses some electricity during charging and discharge.",
    "Specify both power in kW or MW and stored energy in kWh or MWh. A 5 MW, 10 MWh system has a nominal two-hour duration at rated power before accounting for operating limits and losses.",
    "Choose a use case before choosing a battery. Backup, peak reduction and renewable balancing each need a different dispatch plan. Safety systems, warranty throughput, temperature management and end-of-life responsibilities belong in the evaluation.",
  ],
  [
    "Solar",
    "Solar vs conventional electricity",
    "Compare how power is produced, bought and used.",
    "On-site solar converts sunlight into electricity where it is needed. Grid electricity provides supply through an interconnected network with a changing generation mix. Most commercial solar projects continue to rely on that network outside productive solar hours.",
    "Compare the cost of self-consumed solar with the electricity it actually displaces. Fixed charges, export rules and time-varying tariffs can change the economics. Annual output and annual demand totals alone can hide an hourly mismatch.",
    "A balanced comparison considers reliability, maintenance responsibilities, financing and environmental boundaries. Battery storage can shift output but adds cost and energy losses. The right arrangement depends on the demand profile.",
  ],
  [
    "Wind",
    "Understanding wind energy",
    "From local wind resource to dependable generation.",
    "Wind turbines convert moving air into mechanical rotation and then electricity. Available energy changes strongly with wind speed, so a credible resource assessment is essential before estimating output.",
    "Turbine placement considers terrain, wakes from neighbouring turbines, access and connection infrastructure. The best layout balances energy yield with environmental constraints, construction practicality and long-term service access.",
    "Monitor actual output against the available wind resource. Lower generation can reflect low wind rather than an equipment fault. Resource-adjusted performance, availability and maintenance records together support better decisions.",
  ],
  [
    "Solar",
    "The business case for commercial solar",
    "A practical checklist for buildings with daytime demand.",
    "Commercial buildings often use electricity during the same hours that solar generates. That overlap can improve self-consumption, especially when lighting, cooling and equipment create a consistent daytime load.",
    "Assess roof life, ownership, structural condition and access. Confirm whether the system will be owned, financed or supplied under a power-purchase arrangement. Compare contracts using the same production and tariff assumptions.",
    "Plan monitoring and maintenance from the beginning. Define responsibilities for roof works, inverter faults and energy reporting. Savings should be reviewed against a documented baseline and actual operating conditions.",
  ],
  [
    "Smart grids",
    "How smart grids work",
    "Better information for a more flexible electricity system.",
    "A smart grid uses measurement, communication and controls to coordinate electricity supply and demand. Meters and sensors help operators understand flows and respond to changing conditions.",
    "At a building level, interval metering can reveal demand peaks and out-of-hours use. Controllers may schedule flexible loads or batteries within agreed safety and operating limits.",
    "Connectivity alone is not enough. Data quality, cybersecurity, device compatibility and clear operating responsibilities determine whether information becomes useful action. Start with a defined problem and measure the outcome.",
  ],
  [
    "Agriculture",
    "Renewable energy for agriculture",
    "Match clean power to real seasonal needs.",
    "Solar can support irrigation, processing, cold storage and other farm activities. Each application has different hours of use and reliability requirements, making seasonal demand an important design input.",
    "Size systems using pump or equipment requirements and the expected operating schedule. Water availability and efficient irrigation remain essential; extra electricity does not remove water constraints.",
    "Consider maintenance access, component availability and backup needs. For cold storage, insulation and efficient refrigeration can reduce the required energy investment. A combined efficiency and renewable plan often deserves evaluation.",
  ],
  [
    "Sustainability",
    "Understanding net zero",
    "A clear distinction between reducing and balancing emissions.",
    "A net-zero strategy starts with an emissions inventory and a defined organizational boundary. Direct emissions, purchased energy and relevant value-chain emissions should be distinguished rather than mixed into one unexplained number.",
    "Prioritize practical emissions reductions: improve efficiency, reduce waste and evaluate low-carbon energy. Set interim milestones and explain which activities the targets cover.",
    "Disclose how residual emissions are addressed and avoid presenting every renewable project as a net-zero outcome. Factors, reporting periods and assumptions must remain visible so progress can be assessed consistently.",
  ],
  [
    "Industry",
    "Green energy for manufacturing",
    "Decarbonization built around production realities.",
    "Manufacturing energy needs include electricity, heating and sometimes high-temperature processes. Renewable electricity can support part of the transition, while thermal demand may require different technologies and operational changes.",
    "Map energy use by process and time. Reliable production can require redundancy, power-quality controls and a carefully planned connection. Efficiency upgrades may lower the capacity needed for a renewable system.",
    "Evaluate options with production teams. Schedule commissioning to manage disruption, establish operating limits and track energy per unit of output. Absolute consumption and production-adjusted performance provide different useful perspectives.",
  ],
  [
    "EV charging",
    "EV charging powered by renewables",
    "Plan the charging schedule before the charging station.",
    "Electric vehicle charging introduces a new load that may be flexible in time. Workplace fleets and vehicles with long dwell times can sometimes align charging with solar production.",
    "Calculate vehicle energy needs, arrival and departure times and existing connection capacity. Smart charging can sequence loads to stay within an agreed limit, while fast charging serves different operational needs.",
    "Renewable generation and charging rarely match perfectly throughout the year. Model grid imports, export limits and optional battery storage before claiming that charging is fully renewable. Include access, safety and future expansion in the layout.",
  ],
  [
    "Sustainability",
    "Reducing business carbon emissions",
    "Turn an inventory into a practical action list.",
    "A useful carbon plan begins with consistent activity data such as fuel use and purchased electricity. Document the calculation method, emission factors and reporting period so results can be compared over time.",
    "Identify the largest sources and distinguish changes caused by lower output from improvements in efficiency. Set owners, budgets and review dates for the actions that are feasible now.",
    "Renewable procurement is one option alongside efficient equipment, operational improvements and reduced waste. Avoid double-counting benefits across projects and describe any claims tied to environmental attributes.",
  ],
  [
    "Technology",
    "What comes next in clean energy",
    "Evaluate new ideas with a practical engineering lens.",
    "Clean energy development includes improved controls, longer-duration storage and better integration between electricity, transport and industrial processes. Useful innovation solves a clear operating problem rather than adding complexity for its own sake.",
    "Assess readiness, service support, safety, integration requirements and lifecycle cost. Pilot results should include the conditions under which performance was measured and the limits of extrapolating those results.",
    "Build room for learning into a deployment plan. Good instrumentation and documented acceptance criteria help distinguish a promising concept from a repeatable solution. Scale after the operating evidence supports the decision.",
  ],
];
